# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0003_auto_20161116_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='game_no',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='round_no',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
